//! Compile Forth AST to Lua code for the hllset CLI runtime.
//!
//! The compiler tracks a virtual stack to map Forth stack operations
//! to Lua variable assignments. Each stack position maps to a Lua variable
//! name (s0, s1, s2, ...). The final stack state is returned as a Lua table.

use crate::ast::{Ast, Word};

/// Compile a Forth AST into a Lua script string suitable for `hllset -e '...'`.
///
/// Returns the Lua source code. Run it with `hllset -e '...'` or the REPL.
pub fn compile_to_lua(ast: &Ast) -> String {
    let mut lua = String::new();
    let mut stack: Vec<String> = Vec::new(); // virtual stack of Lua variable names
    let mut var_counter = 0;
    let mut values: std::collections::HashMap<String, f64> = std::collections::HashMap::new();

    lua.push_str("-- Generated by hllset-forth\n");

    for word in &ast.words {
        compile_word(word, &mut lua, &mut stack, &mut var_counter, &mut values);
    }

    // Return the stack as a Lua array
    if stack.is_empty() {
        lua.push_str("return {}\n");
    } else {
        lua.push_str("return {");
        for (i, v) in stack.iter().enumerate() {
            if i > 0 {
                lua.push_str(", ");
            }
            lua.push_str(v);
        }
        lua.push_str("}\n");
    }

    lua
}

fn compile_word(
    word: &Word,
    lua: &mut String,
    stack: &mut Vec<String>,
    counter: &mut usize,
    values: &mut std::collections::HashMap<String, f64>,
) {
    // Compile-time known values for constant propagation
    // Rebuild values from previous lua output (hack: parse from comments)
    for line in lua.lines() {
        if line.starts_with("-- value:") {
            let parts: Vec<&str> = line[9..].splitn(2, '=').collect();
            if parts.len() == 2 {
                if let Ok(n) = parts[1].trim().parse::<f64>() {}
            }
        }
    }
    match word {
        Word::Str(s) => {
            let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
            let v = new_var(counter);
            lua.push_str(&format!("{} = \"{}\"\n", v, escaped));
            stack.push(v);
        }
        Word::Num(n) => {
            let v = new_var(counter);
            lua.push_str(&format!("{} = {}\n", v, n));
            values.insert(v.clone(), *n);
            stack.push(v);
        }
        Word::Ident(name) => {
            match name.to_uppercase().as_str() {
                // Stack manipulation
                "DUP" => {
                    if let Some(top) = stack.last() {
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = {}\n", v, top));
                        stack.push(v);
                    }
                }
                "SWAP" => {
                    if stack.len() >= 2 {
                        let a = stack.pop().unwrap();
                        let b = stack.pop().unwrap();
                        stack.push(a);
                        stack.push(b);
                    }
                }
                "DROP" => {
                    stack.pop();
                }
                "OVER" => {
                    if stack.len() >= 2 {
                        let second = &stack[stack.len() - 2];
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = {}\n", v, second));
                        stack.push(v);
                    }
                }
                "ROT" => {
                    if stack.len() >= 3 {
                        let c = stack.pop().unwrap();
                        let b = stack.pop().unwrap();
                        let a = stack.pop().unwrap();
                        stack.push(b);
                        stack.push(c);
                        stack.push(a);
                    }
                }

                // HLLSet creation
                "INSCRIBE" => {
                    if let Some(count_var) = stack.pop() {
                        let count: usize = values.get(&count_var).map(|n| *n as usize).unwrap_or(1);
                        let mut token_vars = Vec::new();
                        for _ in 0..count {
                            if let Some(tv) = stack.pop() {
                                token_vars.push(tv);
                            }
                        }
                        token_vars.reverse();
                        let v = new_var(counter);
                        let table_lua = token_vars.join(", ");
                        lua.push_str(&format!("{} = hllset.inscribe({{ {} }})\n", v, table_lua));
                        stack.push(v);
                    }
                }
                "TOKENIZE" => {
                    if let Some(text) = stack.pop() {
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = hllset.tokenize({})\n", v, text));
                        stack.push(v);
                    }
                }
                "EMPTY" => {
                    let v = new_var(counter);
                    lua.push_str(&format!("{} = hllset.empty()\n", v));
                    stack.push(v);
                }

                // Set algebra
                "UNION" => binary_op(lua, stack, counter, "+"),
                "INTERSECT" => binary_op(lua, stack, counter, "*"),
                "DIFF" => binary_op(lua, stack, counter, "-"),
                "CARD" => {
                    if let Some(h) = stack.pop() {
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = #{}\n", v, h));
                        stack.push(v);
                    }
                }
                "POPCOUNT" => {
                    if let Some(h) = stack.pop() {
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = {}:popcount()\n", v, h));
                        stack.push(v);
                    }
                }
                "BSS" => {
                    if stack.len() >= 2 {
                        let b = stack.pop().unwrap();
                        let a = stack.pop().unwrap();
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = {}:bss_inclusion({})\n", v, a, b));
                        stack.push(v);
                    }
                }
                "JACCARD" => {
                    if stack.len() >= 2 {
                        let b = stack.pop().unwrap();
                        let a = stack.pop().unwrap();
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = {}:jaccard({})\n", v, a, b));
                        stack.push(v);
                    }
                }

                // Storage (HLPP)
                "STORE" => {
                    if let Some(h) = stack.pop() {
                        lua.push_str(&format!("hllset.store({})\n", h));
                    }
                }
                "LOAD" => {
                    if let Some(cid) = stack.pop() {
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = hllset.load({})\n", v, cid));
                        stack.push(v);
                    }
                }
                "LIST" => {
                    if let Some(prefix) = stack.pop() {
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = hllset.list({})\n", v, prefix));
                        stack.push(v);
                    }
                }
                "PIN" => {
                    if let Some(cid) = stack.pop() {
                        lua.push_str(&format!("hllset.pin({})\n", cid));
                    }
                }
                "UNPIN" => {
                    if let Some(cid) = stack.pop() {
                        lua.push_str(&format!("hllset.unpin({})\n", cid));
                    }
                }
                "GC" => {
                    let v = new_var(counter);
                    lua.push_str(&format!("{} = hllset.gc()\n", v));
                    stack.push(v);
                }
                "KEY" => {
                    if let Some(h) = stack.pop() {
                        let v = new_var(counter);
                        lua.push_str(&format!("{} = {}:key()\n", v, h));
                        stack.push(v);
                    }
                }

                // Unknown word — treat as a no-op (push as string)
                _ => {
                    let v = new_var(counter);
                    lua.push_str(&format!("{} = \"{}\"\n", v, name));
                    stack.push(v);
                }
            }
        }
        Word::Seq(_words) => {
            // Sequences not yet supported in compilation
        }
        Word::ColonDef { name, body } => {
            // Emit as a Lua function definition.
            // The body is compiled inline at definition site;
            // at call site, the name becomes a Lua function call.
            lua.push_str(&format!("function {name}()\n"));
            let mut body_stack: Vec<String> = Vec::new();
            let mut body_counter = 0;
            let mut body_values = std::collections::HashMap::new();
            for w in body {
                compile_word(w, lua, &mut body_stack, &mut body_counter, &mut body_values);
            }
            // Return the top of stack (or empty table)
            if body_stack.is_empty() {
                lua.push_str("  return {}\n");
            } else if body_stack.len() == 1 {
                lua.push_str(&format!("  return {}\n", body_stack[0]));
            } else {
                lua.push_str("  return {");
                for (i, v) in body_stack.iter().enumerate() {
                    if i > 0 {
                        lua.push_str(", ");
                    }
                    lua.push_str(v);
                }
                lua.push_str("}\n");
            }
            lua.push_str("end\n");

            // Push the function name onto the stack so it can be called
            let v = new_var(counter);
            lua.push_str(&format!("{v} = {name}()\n"));
            stack.push(v);
        }
    }
}

fn new_var(counter: &mut usize) -> String {
    *counter += 1;
    format!("v{}", *counter - 1)
}

fn binary_op(lua: &mut String, stack: &mut Vec<String>, counter: &mut usize, op: &str) {
    if stack.len() >= 2 {
        let b = stack.pop().unwrap();
        let a = stack.pop().unwrap();
        let v = new_var(counter);
        lua.push_str(&format!("{} = {} {} {}\n", v, a, op, b));
        stack.push(v);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse;

    #[test]
    fn test_empty_forth() {
        let ast = parse("").unwrap();
        let lua = compile_to_lua(&ast);
        assert!(lua.contains("return {}"));
    }

    #[test]
    fn test_inscribe_compile() {
        let ast = parse(r#""hello" "world" 2 INSCRIBE"#).unwrap();
        let lua = compile_to_lua(&ast);
        // Should contain hllset.inscribe call
        assert!(lua.contains("hllset.inscribe"));
        assert!(lua.contains("\"hello\""));
        assert!(lua.contains("\"world\""));
    }

    #[test]
    fn test_intersect_compile() {
        let ast = parse(r#""a" "b" 2 INSCRIBE "b" "c" 2 INSCRIBE INTERSECT"#).unwrap();
        let lua = compile_to_lua(&ast);
        assert!(lua.contains("hllset.inscribe"));
        assert!(lua.contains("*")); // the INTERSECT operator
    }

    #[test]
    fn test_store_load_compile() {
        let ast = parse(r#""test" 1 INSCRIBE DUP STORE KEY LOAD"#).unwrap();
        let lua = compile_to_lua(&ast);
        assert!(lua.contains("hllset.store"));
        assert!(lua.contains("hllset.load"));
        assert!(lua.contains(":key()"));
    }

    #[test]
    fn test_bss_compile() {
        let ast = parse(r#""a" 1 INSCRIBE "b" 1 INSCRIBE BSS"#).unwrap();
        let lua = compile_to_lua(&ast);
        assert!(lua.contains("bss_inclusion"));
    }

    #[test]
    fn test_colon_def_compile() {
        let src = r#": GREET "hello world" ;"#;
        let ast = parse(src).unwrap();
        // Should have one ColonDef
        assert_eq!(ast.words.len(), 1);
        let lua = compile_to_lua(&ast);
        assert!(lua.contains("function GREET()"));
        assert!(lua.contains("hello world"));
        assert!(lua.contains("end"));
    }
}
